export const CANONICAL_ODDS_KEYS: Record<string, string[]> = {
  color: [
    'green',
    'red',
    'violet',
    'green_violet',
    'red_violet',
    'big',
    'small',
    'number',
  ],
  dice: [
    'sum_big',
    'sum_small',
    'sum_odd',
    'sum_even',
    'sum_three',
    'sum_four',
    'sum_five',
    'sum_six',
    'sum_seven',
    'sum_eight',
    'sum_nine',
    'sum_ten',
    'sum_eleven',
    'sum_twelve',
    'sum_thirteen',
    'sum_fourteen',
    'sum_fifteen',
    'sum_sixteen',
    'sum_seventeen',
    'sum_eighteen',
    'single_one',
    'single_two',
    'single_three',
    'single_four',
    'single_five',
    'single_six',
    'double_one',
    'double_two',
    'double_three',
    'double_four',
    'double_five',
    'double_six',
    'leopard_any',
    'leopard_one',
    'leopard_two',
    'leopard_three',
    'leopard_four',
    'leopard_five',
    'leopard_six',
  ],
  race: ['champion', 'top3_fixed', 'winning_group', 'top3_any', 'top3_random'],
  digit3: [
    'exact',
    'box',
    'front2',
    'back2',
    'sum_big',
    'sum_small',
    'sum_odd',
    'sum_even',
    'sum',
  ],
  digit5: [
    'big',
    'small',
    'odd',
    'even',
    'first',
    'second',
    'third',
    'fourth',
    'fifth',
    'sum',
    'exact5',
    'exact4',
    'first4',
    'first3',
    'first2',
    'first1',
  ],
  single_digit: ['number'],
  lottery: [
    'first',
    'second',
    'third',
    'fourth',
    'fifth',
    'consolation',
    'last4',
    'last3',
    'last2',
    'last1',
  ],
  lottery_punjab: ['exact', 'last4', 'last3', 'last2'],
  custom: [],
};

export function resolveOddsClass(
  code: string,
  aliasMap: Record<string, string> = {},
): string {
  if (!code) return code;
  if (aliasMap[code]) return aliasMap[code];

  const m = /^([a-z_]+?)_(\d+)$/.exec(code);
  if (m) {
    const base = m[1];
    return base;
  }
  return code;
}
