export enum TransactionType {
  Recharge = 'recharge',
  Withdraw = 'withdraw',
  Bet = 'bet',
  Win = 'win',
  WinBonus = 'win_bonus',
  WheelDraw = 'wheel_draw',
  BoxDraw = 'box_draw',
  Payout = 'payout',
  Refund = 'refund',
  Commission = 'commission',
  Rebate = 'rebate',
  Bonus = 'bonus',
  Wage = 'wage',
  Adjust = 'adjust',
  Checkin = 'checkin',
  RankReward = 'rank_reward',
  VipAward = 'vip_award',
  Transfer = 'transfer',
  Cdkey = 'cdkey',
  CashRain = 'cashrain',
  ThirdPartyBet = 'third_party_bet',
  ThirdPartyWin = 'third_party_win',
}
